### PR TITLE
Fix broken link to Orb Registry [semver:skip]

### PR DESCRIPTION
**Pull request by digitalmaster**

### CODE REVIEW

**Review by erichaberkorn — APPROVED** [review]
Thank you

**Comment by gmemstr** [comment]
Should the references to the sandbox namespace orb be updated to the public one? This will give us an accurate version number :)

**Comment by digitalmaster** [comment]
@gmemstr Ah yes.. good call..

**Comment by digitalmaster** [comment]
Yup that did the trick 👍 

Thanks @gmemstr 🙏

**Review by gmemstr — APPROVED** [review]

**Review by fritzhienz — COMMENTED** [review]
-

**Pull request merged**
